FROM golang:1.13.3
MAINTAINER kurneko<nekomokomoko@gmail.com>

RUN go get -u github.com/golang/dep/cmd/dep
RUN go get -u golang.org/x/tools/cmd/goimports
RUN go get -u github.com/mitchellh/gox
RUN go get -u github.com/haya14busa/goverage
